### ISSUE TITLE
Consider updating to Redux 1.0 RC

### ISSUE THREAD

**Issue by gaearon** [danharper/playing-with-react-and-redux#1]
Redux 1.0 RC is out with breaking changes. **No further API changes are expected in 1.0 so it may be a good time to port the example to 1.0 RC (in a branch).** We will release 1.0 when the docs are ready.

You can find the comprehensive list of the changes in 1.0 RC against 1.0 alpha in the **[Redux 1.0 RC release notes](https://github.com/gaearon/redux/releases/tag/v1.0.0-rc)**. If you haven't ported to alpha yet, you'll need to **[apply changes from 0.12 to alpha first](https://github.com/gaearon/redux/pull/195#issue-92206321)**.

Thank you!
Please make sure to report any issues so we can release a stable 1.0.

**Comment by danharper** [comment]
:+1: Was just reading over the release notes :) Will update in the next couple of days, still doing some work to improve this further.

**Comment by gaearon** [comment]
Thank you!

**Comment by danharper** [comment]
Done with:
- ace82db1e0ba32048914aca94608bae40d54bb48 (upgrade)
- a699a5606fcb7aad34a7cc99a1d8a76de63d7a86 (renaming)
- 2980326883f20d1c9cffd85bacf40f7c9c7cc38b (clearer store creation)
